### ISSUE TITLE
Feature Request: Auto-accept suggestions

### ISSUE THREAD

**Issue by fgather** [OrfeasZ/GrooveCaster#1]
see title..

with the option to only accept songs in the collection, or maybe songs with the same name (since there are usually more versions of the same song uploaded)

**Comment by OrfeasZ** [comment]
This is easily achievable using the module system.
You can find a sample module which automatically approves suggestion after 3 upvotes [here](https://github.com/OrfeasZ/GrooveCaster/wiki/Sample-Modules#suggestion-manager).
