### ISSUE TITLE
Feature request: GrooveCaster as a hostable ASP.NET Application 

### ISSUE THREAD

**Issue by gsclassics** [OrfeasZ/GrooveCaster#10]
Would be great to have a package ready to be installed using an existing IIS (for Windows servers) and also a package ready to be installed in an apache web server (for Unix servers).

This app as standalone web service is really useful but you need a public IP in order to make the app available in Internet.
Giving the possibility to host it in an external Hosting server will make it easier to use it as THE Broadcasts manager.

**Comment by OrfeasZ** [comment]
An ASP.NET module of GrooveCaster will be provided in the next release.
As for running it on a Linux server with Apache or Nginx, you can follow the [instructions](https://github.com/OrfeasZ/GrooveCaster#unix-environments) on how to install it as a service, and then proxy it through Apache or Nginx, using mod_proxy and proxy_pass respectively.

**Comment by OrfeasZ** [comment]
I will be making a separate issue for Debian installation packages.
