### ISSUE TITLE
When installing it in some window hosts, Nancy.ViewEngines.ViewNotFoundException raises

### ISSUE THREAD

**Issue by gsclassics** [OrfeasZ/GrooveCaster#5]
I tried to install it in a windows 8.1 Pro virtual machine with .NET framework 4.5 installed.
When accessing to the web app, the following Exception appears in the browser:
"Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'Login'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views/Auth/Login-en-US,views/Auth/Login,Auth/Login-en-US,Auth/Login,views/Login-en-US,views/Login,Login-en-US,Login"

Tried also to start it as a daemon and to open it in a console as administrator. Same error appears.

**Comment by OrfeasZ** [comment]
I just released Version [1.1.2.0](https://github.com/OrfeasZ/GrooveCaster/releases/tag/1.1.2.0) which fixes this issue.
Try it out and let me know if you have any additional issues.

If not, feel free to close this issue.

**Comment by gsclassics** [comment]
you are really fast! It works now. Thanks!
