### ISSUE TITLE
Feature Request: import Favorites or specific playlists instead of full collection

### ISSUE THREAD

**Issue by gsclassics** [OrfeasZ/GrooveCaster#6]
Adding songs: Would be great to import specific playlists or just the favorites.

**Comment by OrfeasZ** [comment]
Playlist support is a feature something that's basically next in my roadmap.
As for favorites, it should also be fairly easy to do.

I'll update this issue with progress on this.

**Comment by gsclassics** [comment]
I miss the possibility to change what will be played in an easy way... the queue management is not easy using the web UI.
I was using your bot today during the normal BC, but later, I started a special broadcast. I had to take over the BC manually and then modify the queue from there, losing the Bot functionalities.

**Comment by OrfeasZ** [comment]
Upcoming feature:
![](http://i.nofate.me/QrTxQBjX.png)

**Comment by OrfeasZ** [comment]
I'm also introducing several changes which will allow module authors to introduce completely custom queuing logic.

**Comment by gsclassics** [comment]
Great Orfeas! you are a machine ;)
A "Remove All" button would also be useful in order to reset the virtual queue

**Comment by OrfeasZ** [comment]
That's what the "Empty Queue" button at the top is for ;)

**Comment by gsclassics** [comment]
Ops, sorry Orfeas, I've just seen it now... I answered too fast because I'm so excited

**Comment by OrfeasZ** [comment]
Version [1.2.0.0](https://github.com/OrfeasZ/GrooveCaster/releases/tag/1.2.0.0) of GrooveCaster introduces playlist capabilities and advanced queue management.

For more information, check [Playlist Management](https://github.com/OrfeasZ/GrooveCaster#playlist-management) and [Queue Management](https://github.com/OrfeasZ/GrooveCaster#queue-management).
