### ISSUE TITLE
Feature request: Broadcaster shoutouts

### ISSUE THREAD

**Issue by gsclassics** [OrfeasZ/GrooveCaster#8]
Would be great if the broadcaster can send shoutouts (chat announcements) from the Web UI.
In addition, could also be great if shoutouts could also be scheduled to be done periodically.

Now Brodcaster can't write messages to the chat because the broadcaster cannot take over the broadcast.

**Comment by OrfeasZ** [comment]
The next version will introduce a chatbox to the admin dashboard:
![](http://i.nofate.me/l8dV7aZk.png)

As for periodic announcements, you can probably do that with a custom module.
When I get some time I'll write an example and attach it here.

**Comment by gsclassics** [comment]
Great Orfeas, you are implementing a new Grooveshark from scratch!

**Comment by OrfeasZ** [comment]
Well, not quite, but close enough.
Such features are useful for remote management, especially for devices that can't directly access GS (like mobiles, etc.).

**Comment by OrfeasZ** [comment]
Version [1.2.0.0](https://github.com/OrfeasZ/GrooveCaster/releases/tag/1.2.0.0) of GrooveCaster introduces the ability to use the chat via the dashboard, as well as handy Timer class, which can be used by Modules for timing events.

You can find a sample module that sends an announcement to the broadcast chat every 30 seconds [here](https://github.com/OrfeasZ/GrooveCaster/wiki/Sample-Modules#chat-announcer).

**Comment by OrfeasZ** [comment]
Additionally, you can get the name of the currently playing playing (if there is one) by doing something like the following:

``` python
if PlaylistManager.PlaylistActive:
    ChatManager.SendChatMessage('Currently playing from %s.' % PlaylistManager.ActivePlaylist.Name)
```
